// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RentalManager.Api.Data;

#nullable disable

namespace RentalManager.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("RentalManager.Api.Models.AdminUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AdminUsers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAtUtc = new DateTime(2026, 5, 24, 4, 11, 21, 638, DateTimeKind.Utc).AddTicks(8194),
                            PasswordHash = "$2a$11$HlDgIuiyVxHd356KWpNR4OtSocmp5RQNYprtQXuKFl6jBlbaRkq3a",
                            Role = 1,
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("RentalManager.Api.Models.ChargeRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("BillingEndUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("BillingStartUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ContractId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("MeterEnd")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("MeterStart")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PaidAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("UsageUnits")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContractId");

                    b.ToTable("ChargeRecords");
                });

            modelBuilder.Entity("RentalManager.Api.Models.Contract", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContractNo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Deposit")
                        .HasColumnType("TEXT");

                    b.Property<int>("ElectricityRuleType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndDateUtc")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MonthlyRent")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("OccupantCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PaymentIntervalMonths")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PeriodPayableAmount")
                        .HasColumnType("TEXT");

                    b.Property<string>("PropertyAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PropertyName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PropertyUnitId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDateUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TenantId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PropertyUnitId");

                    b.HasIndex("TenantId");

                    b.ToTable("Contracts");
                });

            modelBuilder.Entity("RentalManager.Api.Models.ContractRoom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ContractId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PropertyRoomId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ContractId");

                    b.HasIndex("PropertyRoomId");

                    b.ToTable("ContractRooms");
                });

            modelBuilder.Entity("RentalManager.Api.Models.ElectricityAllocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ContractId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ElectricityBillId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("MeterEnd")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("MeterStart")
                        .HasColumnType("TEXT");

                    b.Property<int>("OccupancyDays")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OccupancyEndUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OccupancyStartUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("OccupantCount")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PayableAmount")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrivateAmount")
                        .HasColumnType("TEXT");

                    b.Property<int>("PropertyRoomId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PublicAmount")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TenantId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TenantUnits")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContractId");

                    b.HasIndex("ElectricityBillId");

                    b.HasIndex("PropertyRoomId");

                    b.HasIndex("TenantId");

                    b.ToTable("ElectricityAllocations");
                });

            modelBuilder.Entity("RentalManager.Api.Models.ElectricityBill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BillingEndUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("BillingStartUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ChargesCreated")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ChargesCreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("ContractId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PayableTotalAmount")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrivateTotalAmount")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PublicTotalAmount")
                        .HasColumnType("TEXT");

                    b.Property<int>("RuleType")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalUnits")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContractId");

                    b.ToTable("ElectricityBills");
                });

            modelBuilder.Entity("RentalManager.Api.Models.ElectricityMeterReading", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("PropertyRoomId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PropertyUnitId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ReadingDateUtc")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ReadingValue")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PropertyUnitId");

                    b.HasIndex("PropertyRoomId", "ReadingDateUtc")
                        .IsUnique();

                    b.ToTable("ElectricityMeterReadings");
                });

            modelBuilder.Entity("RentalManager.Api.Models.ExpenseRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("BillingEndUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("BillingStartUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PropertyRoomId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PropertyUnitId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SplitStatus")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("UsageUnits")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PropertyRoomId");

                    b.HasIndex("PropertyUnitId");

                    b.ToTable("ExpenseRecords");
                });

            modelBuilder.Entity("RentalManager.Api.Models.PropertyRoom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("PropertyUnitId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PropertyUnitId");

                    b.ToTable("PropertyRooms");
                });

            modelBuilder.Entity("RentalManager.Api.Models.PropertyUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PropertyUnits");
                });

            modelBuilder.Entity("RentalManager.Api.Models.Tenant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("BirthdayUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmergencyContactName")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmergencyContactPhone")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("PersonalId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TaxId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("RentalManager.Api.Models.ChargeRecord", b =>
                {
                    b.HasOne("RentalManager.Api.Models.Contract", "Contract")
                        .WithMany()
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contract");
                });

            modelBuilder.Entity("RentalManager.Api.Models.Contract", b =>
                {
                    b.HasOne("RentalManager.Api.Models.PropertyUnit", "PropertyUnit")
                        .WithMany()
                        .HasForeignKey("PropertyUnitId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RentalManager.Api.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PropertyUnit");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("RentalManager.Api.Models.ContractRoom", b =>
                {
                    b.HasOne("RentalManager.Api.Models.Contract", "Contract")
                        .WithMany()
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RentalManager.Api.Models.PropertyRoom", "PropertyRoom")
                        .WithMany()
                        .HasForeignKey("PropertyRoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Contract");

                    b.Navigation("PropertyRoom");
                });

            modelBuilder.Entity("RentalManager.Api.Models.ElectricityAllocation", b =>
                {
                    b.HasOne("RentalManager.Api.Models.Contract", "Contract")
                        .WithMany()
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RentalManager.Api.Models.ElectricityBill", "ElectricityBill")
                        .WithMany()
                        .HasForeignKey("ElectricityBillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RentalManager.Api.Models.PropertyRoom", "PropertyRoom")
                        .WithMany()
                        .HasForeignKey("PropertyRoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RentalManager.Api.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Contract");

                    b.Navigation("ElectricityBill");

                    b.Navigation("PropertyRoom");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("RentalManager.Api.Models.ElectricityBill", b =>
                {
                    b.HasOne("RentalManager.Api.Models.Contract", "Contract")
                        .WithMany()
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contract");
                });

            modelBuilder.Entity("RentalManager.Api.Models.ElectricityMeterReading", b =>
                {
                    b.HasOne("RentalManager.Api.Models.PropertyRoom", "PropertyRoom")
                        .WithMany()
                        .HasForeignKey("PropertyRoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RentalManager.Api.Models.PropertyUnit", "PropertyUnit")
                        .WithMany()
                        .HasForeignKey("PropertyUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PropertyRoom");

                    b.Navigation("PropertyUnit");
                });

            modelBuilder.Entity("RentalManager.Api.Models.ExpenseRecord", b =>
                {
                    b.HasOne("RentalManager.Api.Models.PropertyRoom", "PropertyRoom")
                        .WithMany()
                        .HasForeignKey("PropertyRoomId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RentalManager.Api.Models.PropertyUnit", "PropertyUnit")
                        .WithMany()
                        .HasForeignKey("PropertyUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PropertyRoom");

                    b.Navigation("PropertyUnit");
                });

            modelBuilder.Entity("RentalManager.Api.Models.PropertyRoom", b =>
                {
                    b.HasOne("RentalManager.Api.Models.PropertyUnit", "PropertyUnit")
                        .WithMany()
                        .HasForeignKey("PropertyUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PropertyUnit");
                });
#pragma warning restore 612, 618
        }
    }
}
